name: Deploy Laravel to VPS

on:
  push:
    branches: [master]   # <- dispara quando você fizer push no main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /var/www/leandrodev.com.br

            # Garante que o código no servidor é exatamente o do main
            git fetch origin
            git checkout -B main origin/main
            git reset --hard origin/main

            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            # Se usa Vite, faça o build (senão o manifest some e a página quebra)
            if [ -f package.json ]; then
              npm ci
              npm run build
            fi

            # Limpa e recompõe caches
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan queue:restart
            php artisan optimize
