name: Deploy Laravel to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acessando VPS e rodando comandos
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/leandrodev.com.br

            git fetch origin
            git checkout -B master origin/master
            git reset --hard origin/master

            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            php artisan migrate --force
            php artisan queue:restart
            php artisan optimize
